version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: bank-rest-db
    environment:
      POSTGRES_DB: bank_rest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SCHEMA_NAME: bank_rest
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - back-network

  bank_rest_service:
    image: bank-rest-service
    container_name: bank-rest-service
    environment:
      DATABASE_URL: postgres_db:5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - back-network

volumes:
  postgres_db:

networks:
  back-network:
    driver: bridge

#
# docker-compose.yml — определяет сервисы для разработки и тестирования.
# Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
# - Открыть нужные порты (например, 5432, 8080).
# - Настроить volume для хранения данных БД.
